namespace POS_qu
{
    partial class AccountsForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Panel panelHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.SplitContainer splitMain;
        private System.Windows.Forms.Panel panelLeft;
        private System.Windows.Forms.Label lblSearch;
        private System.Windows.Forms.TextBox txtSearch;
        private System.Windows.Forms.DataGridView dgvAccounts;
        private System.Windows.Forms.Panel panelRight;
        private System.Windows.Forms.GroupBox groupBoxDetail;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.Label lblType;
        private System.Windows.Forms.ComboBox cmbType;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.Button btnEdit;
        private System.Windows.Forms.Button btnDelete;
        private System.Windows.Forms.Button btnRefresh;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            panelHeader = new System.Windows.Forms.Panel();
            lblTitle = new System.Windows.Forms.Label();
            btnClose = new System.Windows.Forms.Button();
            splitMain = new System.Windows.Forms.SplitContainer();
            panelLeft = new System.Windows.Forms.Panel();
            dgvAccounts = new System.Windows.Forms.DataGridView();
            txtSearch = new System.Windows.Forms.TextBox();
            lblSearch = new System.Windows.Forms.Label();
            panelRight = new System.Windows.Forms.Panel();
            groupBoxDetail = new System.Windows.Forms.GroupBox();
            btnRefresh = new System.Windows.Forms.Button();
            btnDelete = new System.Windows.Forms.Button();
            btnEdit = new System.Windows.Forms.Button();
            btnAdd = new System.Windows.Forms.Button();
            cmbType = new System.Windows.Forms.ComboBox();
            lblType = new System.Windows.Forms.Label();
            txtName = new System.Windows.Forms.TextBox();
            lblName = new System.Windows.Forms.Label();
            panelHeader.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)splitMain).BeginInit();
            splitMain.Panel1.SuspendLayout();
            splitMain.Panel2.SuspendLayout();
            splitMain.SuspendLayout();
            panelLeft.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvAccounts).BeginInit();
            panelRight.SuspendLayout();
            groupBoxDetail.SuspendLayout();
            SuspendLayout();
            panelHeader.BackColor = System.Drawing.Color.White;
            panelHeader.Controls.Add(btnClose);
            panelHeader.Controls.Add(lblTitle);
            panelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            panelHeader.Location = new System.Drawing.Point(0, 0);
            panelHeader.Name = "panelHeader";
            panelHeader.Size = new System.Drawing.Size(1200, 70);
            panelHeader.TabIndex = 0;
            lblTitle.AutoSize = true;
            lblTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 16F, System.Drawing.FontStyle.Bold);
            lblTitle.ForeColor = System.Drawing.Color.FromArgb(51, 51, 51);
            lblTitle.Location = new System.Drawing.Point(20, 15);
            lblTitle.Name = "lblTitle";
            lblTitle.Size = new System.Drawing.Size(154, 37);
            lblTitle.TabIndex = 0;
            lblTitle.Text = "Akun (COA)";
            btnClose.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            btnClose.BackColor = System.Drawing.Color.White;
            btnClose.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(200, 200, 200);
            btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnClose.Font = new System.Drawing.Font("Segoe UI", 10F);
            btnClose.Location = new System.Drawing.Point(1040, 15);
            btnClose.Name = "btnClose";
            btnClose.Size = new System.Drawing.Size(140, 40);
            btnClose.TabIndex = 1;
            btnClose.Text = "Tutup";
            btnClose.UseVisualStyleBackColor = false;
            splitMain.Dock = System.Windows.Forms.DockStyle.Fill;
            splitMain.Location = new System.Drawing.Point(0, 70);
            splitMain.Name = "splitMain";
            splitMain.Panel1.Controls.Add(panelLeft);
            splitMain.Panel2.Controls.Add(panelRight);
            splitMain.Size = new System.Drawing.Size(1200, 680);
            splitMain.SplitterDistance = 720;
            splitMain.TabIndex = 1;
            panelLeft.BackColor = System.Drawing.Color.White;
            panelLeft.Controls.Add(dgvAccounts);
            panelLeft.Controls.Add(txtSearch);
            panelLeft.Controls.Add(lblSearch);
            panelLeft.Dock = System.Windows.Forms.DockStyle.Fill;
            panelLeft.Location = new System.Drawing.Point(0, 0);
            panelLeft.Name = "panelLeft";
            panelLeft.Padding = new System.Windows.Forms.Padding(16);
            panelLeft.Size = new System.Drawing.Size(720, 680);
            panelLeft.TabIndex = 0;
            dgvAccounts.AllowUserToAddRows = false;
            dgvAccounts.AllowUserToDeleteRows = false;
            dgvAccounts.BackgroundColor = System.Drawing.Color.White;
            dgvAccounts.BorderStyle = System.Windows.Forms.BorderStyle.None;
            dgvAccounts.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            dgvAccounts.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(245, 246, 250);
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.FromArgb(51, 51, 51);
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            dgvAccounts.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            dgvAccounts.ColumnHeadersHeight = 45;
            dgvAccounts.Dock = System.Windows.Forms.DockStyle.Fill;
            dgvAccounts.EnableHeadersVisualStyles = false;
            dgvAccounts.Location = new System.Drawing.Point(16, 86);
            dgvAccounts.MultiSelect = false;
            dgvAccounts.Name = "dgvAccounts";
            dgvAccounts.ReadOnly = true;
            dgvAccounts.RowHeadersVisible = false;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI", 10F);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(51, 51, 51);
            dataGridViewCellStyle2.Padding = new System.Windows.Forms.Padding(5);
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(232, 240, 254);
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.FromArgb(51, 51, 51);
            dgvAccounts.RowsDefaultCellStyle = dataGridViewCellStyle2;
            dgvAccounts.RowTemplate.Height = 45;
            dgvAccounts.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            dgvAccounts.Size = new System.Drawing.Size(688, 578);
            dgvAccounts.TabIndex = 2;
            txtSearch.Font = new System.Drawing.Font("Segoe UI", 10F);
            txtSearch.Location = new System.Drawing.Point(16, 46);
            txtSearch.Name = "txtSearch";
            txtSearch.Size = new System.Drawing.Size(688, 30);
            txtSearch.TabIndex = 1;
            lblSearch.AutoSize = true;
            lblSearch.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblSearch.Location = new System.Drawing.Point(16, 16);
            lblSearch.Name = "lblSearch";
            lblSearch.Size = new System.Drawing.Size(97, 23);
            lblSearch.TabIndex = 0;
            lblSearch.Text = "Cari Akun:";
            panelRight.BackColor = System.Drawing.Color.Transparent;
            panelRight.Controls.Add(groupBoxDetail);
            panelRight.Dock = System.Windows.Forms.DockStyle.Fill;
            panelRight.Location = new System.Drawing.Point(0, 0);
            panelRight.Name = "panelRight";
            panelRight.Padding = new System.Windows.Forms.Padding(16);
            panelRight.Size = new System.Drawing.Size(476, 680);
            panelRight.TabIndex = 0;
            groupBoxDetail.BackColor = System.Drawing.Color.White;
            groupBoxDetail.Controls.Add(btnRefresh);
            groupBoxDetail.Controls.Add(btnDelete);
            groupBoxDetail.Controls.Add(btnEdit);
            groupBoxDetail.Controls.Add(btnAdd);
            groupBoxDetail.Controls.Add(cmbType);
            groupBoxDetail.Controls.Add(lblType);
            groupBoxDetail.Controls.Add(txtName);
            groupBoxDetail.Controls.Add(lblName);
            groupBoxDetail.Dock = System.Windows.Forms.DockStyle.Top;
            groupBoxDetail.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            groupBoxDetail.Location = new System.Drawing.Point(16, 16);
            groupBoxDetail.Name = "groupBoxDetail";
            groupBoxDetail.Padding = new System.Windows.Forms.Padding(16);
            groupBoxDetail.Size = new System.Drawing.Size(444, 320);
            groupBoxDetail.TabIndex = 0;
            groupBoxDetail.TabStop = false;
            groupBoxDetail.Text = "Detail Akun";
            btnRefresh.BackColor = System.Drawing.Color.White;
            btnRefresh.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(200, 200, 200);
            btnRefresh.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnRefresh.Font = new System.Drawing.Font("Segoe UI", 10F);
            btnRefresh.Location = new System.Drawing.Point(320, 250);
            btnRefresh.Name = "btnRefresh";
            btnRefresh.Size = new System.Drawing.Size(105, 40);
            btnRefresh.TabIndex = 8;
            btnRefresh.Text = "Refresh";
            btnRefresh.UseVisualStyleBackColor = false;
            btnDelete.BackColor = System.Drawing.Color.White;
            btnDelete.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(200, 200, 200);
            btnDelete.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnDelete.Font = new System.Drawing.Font("Segoe UI", 10F);
            btnDelete.Location = new System.Drawing.Point(207, 250);
            btnDelete.Name = "btnDelete";
            btnDelete.Size = new System.Drawing.Size(105, 40);
            btnDelete.TabIndex = 7;
            btnDelete.Text = "Hapus";
            btnDelete.UseVisualStyleBackColor = false;
            btnEdit.BackColor = System.Drawing.Color.White;
            btnEdit.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(200, 200, 200);
            btnEdit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnEdit.Font = new System.Drawing.Font("Segoe UI", 10F);
            btnEdit.Location = new System.Drawing.Point(94, 250);
            btnEdit.Name = "btnEdit";
            btnEdit.Size = new System.Drawing.Size(105, 40);
            btnEdit.TabIndex = 6;
            btnEdit.Text = "Ubah";
            btnEdit.UseVisualStyleBackColor = false;
            btnAdd.BackColor = System.Drawing.Color.FromArgb(0, 120, 215);
            btnAdd.FlatAppearance.BorderSize = 0;
            btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnAdd.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            btnAdd.ForeColor = System.Drawing.Color.White;
            btnAdd.Location = new System.Drawing.Point(20, 250);
            btnAdd.Name = "btnAdd";
            btnAdd.Size = new System.Drawing.Size(66, 40);
            btnAdd.TabIndex = 5;
            btnAdd.Text = "Add";
            btnAdd.UseVisualStyleBackColor = false;
            cmbType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbType.Font = new System.Drawing.Font("Segoe UI", 10F);
            cmbType.FormattingEnabled = true;
            cmbType.Location = new System.Drawing.Point(20, 170);
            cmbType.Name = "cmbType";
            cmbType.Size = new System.Drawing.Size(405, 31);
            cmbType.TabIndex = 4;
            lblType.AutoSize = true;
            lblType.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblType.Location = new System.Drawing.Point(20, 140);
            lblType.Name = "lblType";
            lblType.Size = new System.Drawing.Size(48, 23);
            lblType.TabIndex = 2;
            lblType.Text = "Type";
            txtName.Font = new System.Drawing.Font("Segoe UI", 10F);
            txtName.Location = new System.Drawing.Point(20, 92);
            txtName.Name = "txtName";
            txtName.Size = new System.Drawing.Size(405, 30);
            txtName.TabIndex = 3;
            lblName.AutoSize = true;
            lblName.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblName.Location = new System.Drawing.Point(20, 62);
            lblName.Name = "lblName";
            lblName.Size = new System.Drawing.Size(57, 23);
            lblName.TabIndex = 1;
            lblName.Text = "Nama";
            AutoScaleDimensions = new System.Drawing.SizeF(10F, 25F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(245, 246, 250);
            ClientSize = new System.Drawing.Size(1200, 750);
            Controls.Add(splitMain);
            Controls.Add(panelHeader);
            Font = new System.Drawing.Font("Segoe UI", 10F);
            MinimumSize = new System.Drawing.Size(1000, 700);
            Name = "AccountsForm";
            Text = "Akun (COA)";
            panelHeader.ResumeLayout(false);
            panelHeader.PerformLayout();
            splitMain.Panel1.ResumeLayout(false);
            splitMain.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)splitMain).EndInit();
            splitMain.ResumeLayout(false);
            panelLeft.ResumeLayout(false);
            panelLeft.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvAccounts).EndInit();
            panelRight.ResumeLayout(false);
            groupBoxDetail.ResumeLayout(false);
            groupBoxDetail.PerformLayout();
            ResumeLayout(false);
        }
    }
}

