namespace POS_qu
{
    partial class PromotionProgramForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Panel panelHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.Panel panelBody;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.Label lblType;
        private System.Windows.Forms.ComboBox cmbType;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.ComboBox cmbStatus;
        private System.Windows.Forms.Label lblPeriod;
        private System.Windows.Forms.DateTimePicker dtStart;
        private System.Windows.Forms.DateTimePicker dtEnd;
        private System.Windows.Forms.CheckBox chkUsePeriod;
        private System.Windows.Forms.Label lblPriority;
        private System.Windows.Forms.NumericUpDown numPriority;
        private System.Windows.Forms.GroupBox grpConfig;
        private System.Windows.Forms.Panel pnlDiskon;
        private System.Windows.Forms.RadioButton rbDiskonPersen;
        private System.Windows.Forms.RadioButton rbDiskonNominal;
        private System.Windows.Forms.NumericUpDown numDiskonValue;
        private System.Windows.Forms.Label lblDiskonValue;
        private System.Windows.Forms.Panel pnlPromo;
        private System.Windows.Forms.Label lblBuyQty;
        private System.Windows.Forms.NumericUpDown numBuyQty;
        private System.Windows.Forms.Label lblGetQty;
        private System.Windows.Forms.NumericUpDown numGetQty;
        private System.Windows.Forms.Label lblBonusItem;
        private System.Windows.Forms.TextBox txtBonusItem;
        private System.Windows.Forms.Button btnPickBonus;
        private System.Windows.Forms.Panel pnlCashback;
        private System.Windows.Forms.RadioButton rbCashbackPersen;
        private System.Windows.Forms.RadioButton rbCashbackNominal;
        private System.Windows.Forms.NumericUpDown numCashbackValue;
        private System.Windows.Forms.Label lblCashbackValue;
        private System.Windows.Forms.Label lblCashbackMethod;
        private System.Windows.Forms.ComboBox cmbCashbackMethod;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            panelHeader = new System.Windows.Forms.Panel();
            lblTitle = new System.Windows.Forms.Label();
            btnSave = new System.Windows.Forms.Button();
            btnClose = new System.Windows.Forms.Button();
            panelBody = new System.Windows.Forms.Panel();
            lblName = new System.Windows.Forms.Label();
            txtName = new System.Windows.Forms.TextBox();
            lblType = new System.Windows.Forms.Label();
            cmbType = new System.Windows.Forms.ComboBox();
            lblStatus = new System.Windows.Forms.Label();
            cmbStatus = new System.Windows.Forms.ComboBox();
            lblPeriod = new System.Windows.Forms.Label();
            dtStart = new System.Windows.Forms.DateTimePicker();
            dtEnd = new System.Windows.Forms.DateTimePicker();
            chkUsePeriod = new System.Windows.Forms.CheckBox();
            lblPriority = new System.Windows.Forms.Label();
            numPriority = new System.Windows.Forms.NumericUpDown();
            grpConfig = new System.Windows.Forms.GroupBox();
            pnlDiskon = new System.Windows.Forms.Panel();
            rbDiskonPersen = new System.Windows.Forms.RadioButton();
            rbDiskonNominal = new System.Windows.Forms.RadioButton();
            numDiskonValue = new System.Windows.Forms.NumericUpDown();
            lblDiskonValue = new System.Windows.Forms.Label();
            pnlPromo = new System.Windows.Forms.Panel();
            lblBuyQty = new System.Windows.Forms.Label();
            numBuyQty = new System.Windows.Forms.NumericUpDown();
            lblGetQty = new System.Windows.Forms.Label();
            numGetQty = new System.Windows.Forms.NumericUpDown();
            lblBonusItem = new System.Windows.Forms.Label();
            txtBonusItem = new System.Windows.Forms.TextBox();
            btnPickBonus = new System.Windows.Forms.Button();
            pnlCashback = new System.Windows.Forms.Panel();
            rbCashbackPersen = new System.Windows.Forms.RadioButton();
            rbCashbackNominal = new System.Windows.Forms.RadioButton();
            numCashbackValue = new System.Windows.Forms.NumericUpDown();
            lblCashbackValue = new System.Windows.Forms.Label();
            lblCashbackMethod = new System.Windows.Forms.Label();
            cmbCashbackMethod = new System.Windows.Forms.ComboBox();
            panelHeader.SuspendLayout();
            panelBody.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numPriority).BeginInit();
            grpConfig.SuspendLayout();
            pnlDiskon.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numDiskonValue).BeginInit();
            pnlPromo.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numBuyQty).BeginInit();
            ((System.ComponentModel.ISupportInitialize)numGetQty).BeginInit();
            pnlCashback.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numCashbackValue).BeginInit();
            SuspendLayout();
            panelHeader.BackColor = System.Drawing.Color.White;
            panelHeader.Controls.Add(btnClose);
            panelHeader.Controls.Add(btnSave);
            panelHeader.Controls.Add(lblTitle);
            panelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            panelHeader.Location = new System.Drawing.Point(0, 0);
            panelHeader.Name = "panelHeader";
            panelHeader.Size = new System.Drawing.Size(900, 70);
            panelHeader.TabIndex = 0;
            lblTitle.AutoSize = true;
            lblTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 16F, System.Drawing.FontStyle.Bold);
            lblTitle.ForeColor = System.Drawing.Color.FromArgb(51, 51, 51);
            lblTitle.Location = new System.Drawing.Point(20, 15);
            lblTitle.Name = "lblTitle";
            lblTitle.Size = new System.Drawing.Size(173, 37);
            lblTitle.TabIndex = 0;
            lblTitle.Text = "Buat Program";
            btnSave.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            btnSave.BackColor = System.Drawing.Color.FromArgb(0, 120, 215);
            btnSave.FlatAppearance.BorderSize = 0;
            btnSave.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnSave.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            btnSave.ForeColor = System.Drawing.Color.White;
            btnSave.Location = new System.Drawing.Point(580, 15);
            btnSave.Name = "btnSave";
            btnSave.Size = new System.Drawing.Size(140, 40);
            btnSave.TabIndex = 1;
            btnSave.Text = "Simpan";
            btnSave.UseVisualStyleBackColor = false;
            btnClose.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            btnClose.BackColor = System.Drawing.Color.White;
            btnClose.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(200, 200, 200);
            btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnClose.Font = new System.Drawing.Font("Segoe UI", 10F);
            btnClose.Location = new System.Drawing.Point(730, 15);
            btnClose.Name = "btnClose";
            btnClose.Size = new System.Drawing.Size(150, 40);
            btnClose.TabIndex = 2;
            btnClose.Text = "Tutup";
            btnClose.UseVisualStyleBackColor = false;
            panelBody.Controls.Add(grpConfig);
            panelBody.Controls.Add(numPriority);
            panelBody.Controls.Add(lblPriority);
            panelBody.Controls.Add(chkUsePeriod);
            panelBody.Controls.Add(dtEnd);
            panelBody.Controls.Add(dtStart);
            panelBody.Controls.Add(lblPeriod);
            panelBody.Controls.Add(cmbStatus);
            panelBody.Controls.Add(lblStatus);
            panelBody.Controls.Add(cmbType);
            panelBody.Controls.Add(lblType);
            panelBody.Controls.Add(txtName);
            panelBody.Controls.Add(lblName);
            panelBody.Dock = System.Windows.Forms.DockStyle.Fill;
            panelBody.Location = new System.Drawing.Point(0, 70);
            panelBody.Name = "panelBody";
            panelBody.Padding = new System.Windows.Forms.Padding(16);
            panelBody.Size = new System.Drawing.Size(900, 580);
            panelBody.TabIndex = 1;
            lblName.AutoSize = true;
            lblName.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblName.Location = new System.Drawing.Point(16, 16);
            lblName.Name = "lblName";
            lblName.Size = new System.Drawing.Size(119, 23);
            lblName.TabIndex = 0;
            lblName.Text = "Nama Program";
            txtName.Font = new System.Drawing.Font("Segoe UI", 10F);
            txtName.Location = new System.Drawing.Point(16, 44);
            txtName.Name = "txtName";
            txtName.Size = new System.Drawing.Size(850, 30);
            txtName.TabIndex = 1;
            lblType.AutoSize = true;
            lblType.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblType.Location = new System.Drawing.Point(16, 86);
            lblType.Name = "lblType";
            lblType.Size = new System.Drawing.Size(41, 23);
            lblType.TabIndex = 2;
            lblType.Text = "Tipe";
            cmbType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbType.Font = new System.Drawing.Font("Segoe UI", 10F);
            cmbType.Location = new System.Drawing.Point(16, 114);
            cmbType.Name = "cmbType";
            cmbType.Size = new System.Drawing.Size(250, 31);
            cmbType.TabIndex = 3;
            lblStatus.AutoSize = true;
            lblStatus.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblStatus.Location = new System.Drawing.Point(286, 86);
            lblStatus.Name = "lblStatus";
            lblStatus.Size = new System.Drawing.Size(52, 23);
            lblStatus.TabIndex = 4;
            lblStatus.Text = "Status";
            cmbStatus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbStatus.Font = new System.Drawing.Font("Segoe UI", 10F);
            cmbStatus.Location = new System.Drawing.Point(286, 114);
            cmbStatus.Name = "cmbStatus";
            cmbStatus.Size = new System.Drawing.Size(200, 31);
            cmbStatus.TabIndex = 5;
            lblPeriod.AutoSize = true;
            lblPeriod.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblPeriod.Location = new System.Drawing.Point(16, 160);
            lblPeriod.Name = "lblPeriod";
            lblPeriod.Size = new System.Drawing.Size(58, 23);
            lblPeriod.TabIndex = 6;
            lblPeriod.Text = "Periode";
            dtStart.Font = new System.Drawing.Font("Segoe UI", 10F);
            dtStart.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            dtStart.Location = new System.Drawing.Point(16, 188);
            dtStart.Name = "dtStart";
            dtStart.Size = new System.Drawing.Size(150, 30);
            dtStart.TabIndex = 7;
            dtEnd.Font = new System.Drawing.Font("Segoe UI", 10F);
            dtEnd.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            dtEnd.Location = new System.Drawing.Point(176, 188);
            dtEnd.Name = "dtEnd";
            dtEnd.Size = new System.Drawing.Size(150, 30);
            dtEnd.TabIndex = 8;
            chkUsePeriod.AutoSize = true;
            chkUsePeriod.Font = new System.Drawing.Font("Segoe UI", 10F);
            chkUsePeriod.Location = new System.Drawing.Point(340, 190);
            chkUsePeriod.Name = "chkUsePeriod";
            chkUsePeriod.Size = new System.Drawing.Size(138, 27);
            chkUsePeriod.TabIndex = 9;
            chkUsePeriod.Text = "Gunakan periode";
            chkUsePeriod.UseVisualStyleBackColor = true;
            lblPriority.AutoSize = true;
            lblPriority.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblPriority.Location = new System.Drawing.Point(520, 86);
            lblPriority.Name = "lblPriority";
            lblPriority.Size = new System.Drawing.Size(63, 23);
            lblPriority.TabIndex = 10;
            lblPriority.Text = "Priority";
            numPriority.Font = new System.Drawing.Font("Segoe UI", 10F);
            numPriority.Location = new System.Drawing.Point(520, 114);
            numPriority.Maximum = new decimal(new int[] { 9999, 0, 0, 0 });
            numPriority.Name = "numPriority";
            numPriority.Size = new System.Drawing.Size(120, 30);
            numPriority.TabIndex = 11;
            grpConfig.BackColor = System.Drawing.Color.White;
            grpConfig.Controls.Add(pnlCashback);
            grpConfig.Controls.Add(pnlPromo);
            grpConfig.Controls.Add(pnlDiskon);
            grpConfig.Dock = System.Windows.Forms.DockStyle.Bottom;
            grpConfig.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            grpConfig.Location = new System.Drawing.Point(16, 240);
            grpConfig.Name = "grpConfig";
            grpConfig.Padding = new System.Windows.Forms.Padding(16);
            grpConfig.Size = new System.Drawing.Size(868, 324);
            grpConfig.TabIndex = 12;
            grpConfig.TabStop = false;
            grpConfig.Text = "Konfigurasi";
            pnlDiskon.Dock = System.Windows.Forms.DockStyle.Fill;
            pnlDiskon.Controls.Add(numDiskonValue);
            pnlDiskon.Controls.Add(lblDiskonValue);
            pnlDiskon.Controls.Add(rbDiskonNominal);
            pnlDiskon.Controls.Add(rbDiskonPersen);
            pnlDiskon.Location = new System.Drawing.Point(16, 39);
            pnlDiskon.Name = "pnlDiskon";
            pnlDiskon.Size = new System.Drawing.Size(836, 269);
            pnlDiskon.TabIndex = 0;
            rbDiskonPersen.AutoSize = true;
            rbDiskonPersen.Location = new System.Drawing.Point(10, 10);
            rbDiskonPersen.Name = "rbDiskonPersen";
            rbDiskonPersen.Size = new System.Drawing.Size(75, 27);
            rbDiskonPersen.TabIndex = 0;
            rbDiskonPersen.Text = "Persen";
            rbDiskonPersen.UseVisualStyleBackColor = true;
            rbDiskonNominal.AutoSize = true;
            rbDiskonNominal.Location = new System.Drawing.Point(110, 10);
            rbDiskonNominal.Name = "rbDiskonNominal";
            rbDiskonNominal.Size = new System.Drawing.Size(85, 27);
            rbDiskonNominal.TabIndex = 1;
            rbDiskonNominal.Text = "Nominal";
            rbDiskonNominal.UseVisualStyleBackColor = true;
            lblDiskonValue.AutoSize = true;
            lblDiskonValue.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblDiskonValue.Location = new System.Drawing.Point(10, 55);
            lblDiskonValue.Name = "lblDiskonValue";
            lblDiskonValue.Size = new System.Drawing.Size(92, 23);
            lblDiskonValue.TabIndex = 2;
            lblDiskonValue.Text = "Nilai Diskon";
            numDiskonValue.Font = new System.Drawing.Font("Segoe UI", 10F);
            numDiskonValue.Location = new System.Drawing.Point(10, 85);
            numDiskonValue.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            numDiskonValue.Name = "numDiskonValue";
            numDiskonValue.Size = new System.Drawing.Size(250, 30);
            numDiskonValue.TabIndex = 3;
            pnlPromo.Dock = System.Windows.Forms.DockStyle.Fill;
            pnlPromo.Controls.Add(btnPickBonus);
            pnlPromo.Controls.Add(txtBonusItem);
            pnlPromo.Controls.Add(lblBonusItem);
            pnlPromo.Controls.Add(numGetQty);
            pnlPromo.Controls.Add(lblGetQty);
            pnlPromo.Controls.Add(numBuyQty);
            pnlPromo.Controls.Add(lblBuyQty);
            pnlPromo.Location = new System.Drawing.Point(16, 39);
            pnlPromo.Name = "pnlPromo";
            pnlPromo.Size = new System.Drawing.Size(836, 269);
            pnlPromo.TabIndex = 1;
            lblBuyQty.AutoSize = true;
            lblBuyQty.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblBuyQty.Location = new System.Drawing.Point(10, 12);
            lblBuyQty.Name = "lblBuyQty";
            lblBuyQty.Size = new System.Drawing.Size(61, 23);
            lblBuyQty.TabIndex = 0;
            lblBuyQty.Text = "Buy Qty";
            numBuyQty.Font = new System.Drawing.Font("Segoe UI", 10F);
            numBuyQty.Location = new System.Drawing.Point(10, 40);
            numBuyQty.Maximum = new decimal(new int[] { 9999, 0, 0, 0 });
            numBuyQty.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            numBuyQty.Name = "numBuyQty";
            numBuyQty.Size = new System.Drawing.Size(150, 30);
            numBuyQty.TabIndex = 1;
            numBuyQty.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblGetQty.AutoSize = true;
            lblGetQty.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblGetQty.Location = new System.Drawing.Point(180, 12);
            lblGetQty.Name = "lblGetQty";
            lblGetQty.Size = new System.Drawing.Size(60, 23);
            lblGetQty.TabIndex = 2;
            lblGetQty.Text = "Get Qty";
            numGetQty.Font = new System.Drawing.Font("Segoe UI", 10F);
            numGetQty.Location = new System.Drawing.Point(180, 40);
            numGetQty.Maximum = new decimal(new int[] { 9999, 0, 0, 0 });
            numGetQty.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            numGetQty.Name = "numGetQty";
            numGetQty.Size = new System.Drawing.Size(150, 30);
            numGetQty.TabIndex = 3;
            numGetQty.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblBonusItem.AutoSize = true;
            lblBonusItem.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblBonusItem.Location = new System.Drawing.Point(10, 90);
            lblBonusItem.Name = "lblBonusItem";
            lblBonusItem.Size = new System.Drawing.Size(91, 23);
            lblBonusItem.TabIndex = 4;
            lblBonusItem.Text = "Item Bonus";
            txtBonusItem.Font = new System.Drawing.Font("Segoe UI", 10F);
            txtBonusItem.Location = new System.Drawing.Point(10, 118);
            txtBonusItem.Name = "txtBonusItem";
            txtBonusItem.ReadOnly = true;
            txtBonusItem.Size = new System.Drawing.Size(520, 30);
            txtBonusItem.TabIndex = 5;
            btnPickBonus.BackColor = System.Drawing.Color.White;
            btnPickBonus.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(200, 200, 200);
            btnPickBonus.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnPickBonus.Font = new System.Drawing.Font("Segoe UI", 10F);
            btnPickBonus.Location = new System.Drawing.Point(540, 116);
            btnPickBonus.Name = "btnPickBonus";
            btnPickBonus.Size = new System.Drawing.Size(120, 34);
            btnPickBonus.TabIndex = 6;
            btnPickBonus.Text = "Pilih...";
            btnPickBonus.UseVisualStyleBackColor = false;
            pnlCashback.Dock = System.Windows.Forms.DockStyle.Fill;
            pnlCashback.Controls.Add(cmbCashbackMethod);
            pnlCashback.Controls.Add(lblCashbackMethod);
            pnlCashback.Controls.Add(numCashbackValue);
            pnlCashback.Controls.Add(lblCashbackValue);
            pnlCashback.Controls.Add(rbCashbackNominal);
            pnlCashback.Controls.Add(rbCashbackPersen);
            pnlCashback.Location = new System.Drawing.Point(16, 39);
            pnlCashback.Name = "pnlCashback";
            pnlCashback.Size = new System.Drawing.Size(836, 269);
            pnlCashback.TabIndex = 2;
            rbCashbackPersen.AutoSize = true;
            rbCashbackPersen.Location = new System.Drawing.Point(10, 10);
            rbCashbackPersen.Name = "rbCashbackPersen";
            rbCashbackPersen.Size = new System.Drawing.Size(75, 27);
            rbCashbackPersen.TabIndex = 0;
            rbCashbackPersen.Text = "Persen";
            rbCashbackPersen.UseVisualStyleBackColor = true;
            rbCashbackNominal.AutoSize = true;
            rbCashbackNominal.Location = new System.Drawing.Point(110, 10);
            rbCashbackNominal.Name = "rbCashbackNominal";
            rbCashbackNominal.Size = new System.Drawing.Size(85, 27);
            rbCashbackNominal.TabIndex = 1;
            rbCashbackNominal.Text = "Nominal";
            rbCashbackNominal.UseVisualStyleBackColor = true;
            lblCashbackValue.AutoSize = true;
            lblCashbackValue.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblCashbackValue.Location = new System.Drawing.Point(10, 55);
            lblCashbackValue.Name = "lblCashbackValue";
            lblCashbackValue.Size = new System.Drawing.Size(113, 23);
            lblCashbackValue.TabIndex = 2;
            lblCashbackValue.Text = "Nilai Cashback";
            numCashbackValue.Font = new System.Drawing.Font("Segoe UI", 10F);
            numCashbackValue.Location = new System.Drawing.Point(10, 85);
            numCashbackValue.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            numCashbackValue.Name = "numCashbackValue";
            numCashbackValue.Size = new System.Drawing.Size(250, 30);
            numCashbackValue.TabIndex = 3;
            lblCashbackMethod.AutoSize = true;
            lblCashbackMethod.Font = new System.Drawing.Font("Segoe UI", 10F);
            lblCashbackMethod.Location = new System.Drawing.Point(10, 135);
            lblCashbackMethod.Name = "lblCashbackMethod";
            lblCashbackMethod.Size = new System.Drawing.Size(62, 23);
            lblCashbackMethod.TabIndex = 4;
            lblCashbackMethod.Text = "Metode";
            cmbCashbackMethod.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbCashbackMethod.Font = new System.Drawing.Font("Segoe UI", 10F);
            cmbCashbackMethod.Location = new System.Drawing.Point(10, 163);
            cmbCashbackMethod.Name = "cmbCashbackMethod";
            cmbCashbackMethod.Size = new System.Drawing.Size(250, 31);
            cmbCashbackMethod.TabIndex = 5;
            AutoScaleDimensions = new System.Drawing.SizeF(10F, 25F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(245, 246, 250);
            ClientSize = new System.Drawing.Size(900, 650);
            Controls.Add(panelBody);
            Controls.Add(panelHeader);
            Font = new System.Drawing.Font("Segoe UI", 10F);
            MinimumSize = new System.Drawing.Size(900, 650);
            Name = "PromotionProgramForm";
            Text = "Buat Program";
            panelHeader.ResumeLayout(false);
            panelHeader.PerformLayout();
            panelBody.ResumeLayout(false);
            panelBody.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)numPriority).EndInit();
            grpConfig.ResumeLayout(false);
            pnlDiskon.ResumeLayout(false);
            pnlDiskon.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)numDiskonValue).EndInit();
            pnlPromo.ResumeLayout(false);
            pnlPromo.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)numBuyQty).EndInit();
            ((System.ComponentModel.ISupportInitialize)numGetQty).EndInit();
            pnlCashback.ResumeLayout(false);
            pnlCashback.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)numCashbackValue).EndInit();
            ResumeLayout(false);
        }
    }
}

